name: Tests

on: [push]

env:
  tf-version: 0.13.4

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm test
    - name: Install Terraform
      uses: little-core-labs/install-terraform@master
      with:
          version: ${{ env.tf-version }}
    - name: Terraform version
      run: |
        terraform version

